baseurl = "https://pablodav.github.io/"
languageCode = "en-us"
title = "Pablo Estigarribia's docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-93334116-1"

# true: use pygments-css or false: color-codes directly
pygmentsuseclasses = false

DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "Pablo Estigarribia's docs"
weight = 1

[Languages.es]
title = "Pablo Estigarribia's docs"
weight = 2

[params]
	# General information
	author = "pablodav"
	description = "Pablo Estigarribia's personal docs for sharing sysadmin and devops works"
	copyright = "Released under the MIT license with content licensed with CC BY"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/pablodav/blog"

	#version = "0.1.0"
	#logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu mono"


[social]
	twitter = "p4blod4v"
	github  = "pablodav"
	email   = "pablodav@gmail.com"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

#[[menu.main]]
#	name   = "Posts"
#	url    = "post/"
#	weight = 0

#[[menu.main]]
#	name   = "Getting started"
#	url    = "getting-started/"
#	weight = 10

#[[menu.main]]
#	name   = "Adding content"
#	url    = "adding-content/"
#	weight = 20

#[[menu.main]]
#	name   = "Roadmap"
#	url    = "roadmap/"
#	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


# https://gohugo.io/overview/configuration#configure-blackfriday-rendering
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
